config/routes.rb
MyPage::Application.routes.draw do
  # root
  root to: 'users#home'

  # polling
  get 'users/poll' => 'users#poll'

  # activities
  resources :activities

  # comments
  resources :comments

  # friendships
  get 'friends' => 'friendships#friends'
  get 'friendships/requests' => 'friendships#requests'
  get 'friendships/pending' => 'friendships#pending'
  resources :friendships

  # messages
  get 'messages/received' => 'messages#received'
  get 'messages/sent' => 'messages#sent'
  resources :messages

  # microposts
  resources :microposts do
    resources :comments
  end

  # sesssions
  post 'login' => 'sessions#create'
  get 'login'  => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resource :sessions

  # users
  get 'confirm' => 'users#confirm'
  get 'recover' => 'users#recover'
  resources :users

end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id                   :integer          not null, primary key
#  subject              :string(255)
#  message              :text
#  sender_id            :integer
#  recipient_id         :integer
#  created_at           :datetime
#  updated_at           :datetime
#  removed_by_sender    :boolean          default(FALSE)
#  removed_by_recipient :boolean          default(FALSE)
#  read                 :boolean          default(FALSE)
#

class Message < ActiveRecord::Base
  attr_accessor :recipient_identifier

  belongs_to :sender, class_name: "User", foreign_key: :sender_id
  belongs_to :recipient, class_name: "User", foreign_key: :recipient_id

  has_many :activities, as: :trackable

  validates(:recipient_identifier, presence: true, :if => "recipient_id.nil?")
  validates(:subject, presence: true, length: 1..30)
  validates(:message, presence: true)

  before_save :set_recipient

  default_scope { order('created_at DESC') }

  def remove_user(user)
    self.removed_by_sender = true if user == sender
    self.removed_by_recipient = true if user == recipient
    if removed_by_sender && removed_by_recipient
      self.destroy
    else
      self.save
    end
  end

  def valid_user?(user)
    (sender == user && !removed_by_sender) || (recipient == user && !removed_by_recipient)
  end

private

  def set_recipient
    if recipient_identifier
      recipient = User.find_by_identifier(recipient_identifier)
      self.recipient_id = recipient.try(:id)
    end
    false unless self.recipient_id
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:show, :destroy]
  before_action :correct_users?, only: [:show, :destroy]

  def index
    populate_messages
    prep_new_message
  end

  def received
    session[:active_tab] = 'received'
    redirect_to messages_path
  end

  def sent
    session[:active_tab] = 'sent'
    redirect_to messages_path
  end

  def show
    @message.update_attribute(:read, true) if @message.recipient == current_user
  end

  def new
    session[:active_tab] = 'new'
    redirect_to messages_path(recipient: params[:recipient])
  end

  def create
    @message = current_user.sent_messages.build(message_params)
    return_to = session.delete(:return_to)
    if @message.save
      session[:active_tab] = 'sent'
      flash[:success] = "Message sent."
      track_activity @message, [@message.recipient, @message.sender]
      redirect_to messages_path
    else
      session[:message] = message_params
      session[:active_tab] = 'new'
      flash.now[:error] = "Message failed to send." if @message.valid?
      populate_messages if params[:page] == "index"
      if params[:page]
        render params.delete(:page)
      else
        redirect_to :back
      end
    end
  end

  def destroy
    session[:active_tab] = @message.recipient == current_user ? 'received' : 'sent'
    @message_id = @message.id
    @message.remove_user(current_user)
    respond_to do |format|
      format.html do
        flash[:success] = "Message deleted."
        redirect_to messages_path
      end
      format.js do
      end
    end
  end

private

  def message_params
    params.require(:message).permit(:recipient_identifier, :subject, :message)
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def correct_users?
    validate_users(@message.recipient, @message.sender)
  end

  def prep_new_message
    if session[:message]
      @message = Message.new(session.delete(:message))
    elsif params[:recipient]
      recipient = params[:recipient]
      @message = Message.new(recipient_identifier: recipient)
    else
      @message = Message.new
    end
  end

  def populate_messages
    @received_messages = current_user.received_messages.includes(:sender).where(
      removed_by_recipient: false
    ).paginate( page: params[:received_messages_page])

    @sent_messages = current_user.sent_messages.includes(:recipient).where(
      removed_by_sender: false
    ).paginate(page: params[:sent_messages_page])

    @active_tab = session.delete(:active_tab) ||  params.delete(:active_tab) || "received"
  end

end

app/views/messages/_fields.html.haml
= f.input :recipient_identifier, label: "Recipient", input_html: { autofocus: @message.recipient_identifier.blank? }

= f.input :subject, input_html: { autofocus: !@message.recipient_identifier.blank? }

= f.input :message, as: :text

= f.submit "Send Message", class: "btn btn-primary btn-block"

app/views/messages/_message.html.haml
= content_tag :tr, id: "message_#{message.id}" do
  %td{width: '25%'}
    = format_time message.created_at
  %td{width: '20%'}
    - if message.sender == current_user
      = message.recipient.nil? ? "Deleted" : (link_to message.recipient.username, message.recipient)
    - else
      = message.sender.nil? ? "Deleted" : (link_to message.sender.username, message.sender)
  %td{width: '40%'}
    = link_to message.subject, message
  %td{width: '10%'}
    = link_to (message.read ? "Read" : "Unread"), message
  %td{width: '5%'}
    = link_to '&times;'.html_safe, message_path(message.id), method: :delete, type: 'button', class: 'close', remote: true

app/views/messages/_received_message.html.haml
= content_tag :tr, id: "message_#{message.id}" do
  %td{width: '25%'}
    = format_time message.created_at
  %td{width: '20%'}
    = message.sender.nil? ? "Deleted" : (link_to message.sender.username, message.sender)
  %td{width: '40%'}
    = link_to message.subject, message
  %td{width: '10%'}
    = link_to (message.read ? "Read" : "Unread"), message
  %td{width: '5%'}
    = link_to '&times;'.html_safe, message_path(message.id), method: :delete, type: 'button', class: 'close', remote: true

app/views/messages/_sent_message.html.haml
= content_tag :tr, id: "message_#{message.id}" do
  %td{width: '25%'}
    = format_time message.created_at
  %td{width: '20%'}
    = message.recipient.nil? ? "Deleted" : (link_to message.recipient.username, message.recipient)
  %td{width: '40%'}
    = link_to message.subject, message
  %td{width: '10%'}
    = link_to (message.read ? "Read" : "Unread"), message
  %td{width: '5%'}
    = link_to '&times;'.html_safe, message_path(message.id), method: :delete, type: 'button', class: 'close', remote: true

app/views/messages/destroy.js.erb
$('tr').remove('#message_<%= @message_id %>');

app/views/messages/index.html.haml
- provide :title, "Messages"

%ul#message_tabs.nav.nav-tabs
  = content_tag :li, class: (@active_tab == "received" ? "active" : "") do
    %a{href: "#received_tab", data: {toggle: "tab"}} Received
  = content_tag :li, class: (@active_tab == 'sent' ? "active" : "") do
    %a{href: "#sent_tab", data: {toggle: 'tab'}} Sent
  = content_tag :li, class: (@active_tab == 'new' ? "active" : "") do
    %a{href: "#new_tab", data: {toggle: 'tab'}} New

.tab-content
  = content_tag :div, id: "received_tab", class: "tab-pane#{' active' if @active_tab == 'received'}" do
    %br
    %table.table.table-hover
      %thead
        %tr
          %th{width: '25%'} Date
          %th{width: '20%'} Sender
          %th{width: '40%'} Subject
          %th{width: '10%'} Read
          %th{width: '5%'}
      %tbody
        - if @received_messages.blank?
          %tr
            %td{colspan: 3} No messages found.
        - else
          = render partial: 'received_message', collection: @received_messages, as: :message
    .pull-right
      = will_paginate @received_messages, param_name: :received_messages_page, params: {active_tab: 'received'}
    .clearfix

  = content_tag :div, id: "sent_tab", class: "tab-pane#{' active' if @active_tab == 'sent'}" do
    %br
    %table.table.table-hover
      %thead
        %tr
          %th{width: '25%'} Date
          %th{width: '20%'} Recipient
          %th{width: '40%'} Subject
          %th{width: '10%'} Read
          %th{width: '5%'}
      %tbody
        - if @sent_messages.blank?
          %tr
            %td{colspan: 3} No messages found.
        - else
          = render partial: 'sent_message', collection: @sent_messages, as: :message
    .pull-right
      = will_paginate @sent_messages, param_name: :sent_messages_page, params: {active_tab: 'sent'}
    .clearfix

  = content_tag :div, id: "new_tab", class: "tab-pane#{' active' if @active_tab == 'new'}" do
    %br
    .col-sm-8.col-sm-offset-2
      = simple_form_for @message, html: { role: "form" } do |f|
        %input{name: "page", type: "hidden", value: "index"}
        = render 'fields', f: f
    .clearfix

app/views/messages/show.html.haml
- provide :title, "Message"

- content_for :header do
  %h1
    Message
    = h content_tag :small, @message.subject

.panel.panel-default
  .panel-body
    %p= simple_format @message.message, sanitize: true