config/routes.rb
MyPage::Application.routes.draw do
  # root
  root to: 'users#home'

  # polling
  get 'users/poll' => 'users#poll'

  # activities
  resources :activities

  # comments
  resources :comments

  # friendships
  get 'friends' => 'friendships#friends'
  get 'friendships/requests' => 'friendships#requests'
  get 'friendships/pending' => 'friendships#pending'
  resources :friendships

  # messages
  get 'messages/received' => 'messages#received'
  get 'messages/sent' => 'messages#sent'
  resources :messages

  # microposts
  resources :microposts do
    resources :comments
  end

  # sesssions
  post 'login' => 'sessions#create'
  get 'login'  => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resource :sessions

  # users
  get 'confirm' => 'users#confirm'
  get 'recover' => 'users#recover'
  resources :users

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                :integer          not null, primary key
#  email             :string(255)
#  hashed_password   :string(255)
#  remember_token    :string(255)
#  created_at        :datetime
#  updated_at        :datetime
#  admin             :boolean          default(FALSE)
#  username          :string(255)
#  headline          :string(255)
#  about             :text
#  confirmation_code :string(255)
#  confirmed         :boolean          default(FALSE)
#  new_email         :string(255)
#

require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessor :new_password, :new_password_confirmation, :password

  has_many :microposts, dependent: :destroy
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: :friend_id, dependent: :destroy
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  has_many :sent_messages, class_name: "Message", foreign_key: :sender_id
  has_many :received_messages, class_name: "Message", foreign_key: :recipient_id
  has_many :activities, dependent: :destroy
  has_many :comments

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  WORD_CHARS = /\A\w+\z/

  # username validations
  validates(:username,
            presence: true,
            format: { with: WORD_CHARS },
            length: 3..20)
  validates_uniqueness_of :username, case_sensitive: false

  # email validations
  validates(:email,
            presence: true,
            format: { with: VALID_EMAIL_REGEX })
  validates_uniqueness_of :email, case_sensitive: false

  # password validations
  validates_presence_of :new_password, :if => :password_changed?
  validates_presence_of :new_password_confirmation, :if => :password_changed?
  validates_confirmation_of :new_password, :if => :password_changed?

  before_save :hash_new_password
  before_save  { |user| user.email = email.downcase }
  before_save :create_remember_token

  default_scope { where(confirmed: true).order('lower(username) ASC') }

  def password_changed?
    (!new_password.blank? || hashed_password.blank?) && password.blank?
  end

  def all_microposts
    Micropost.includes(:user).where(user_id: mutual_friends << self)
  end

  def mutual_friends
    friends.where(id: inverse_friends.map { |inverse| inverse.id })
  end

  def mutual_friendships
    friendships.where(friend_id: inverse_friendships.map { |inverse| inverse.user_id })
  end

  def pending_friends
    friends.where.not(id: inverse_friends.map { |inverse| inverse.id})
  end

  def friend_requests
    inverse_friends.where.not(id: friends.map { |friend| friend.id})
  end

  def friend_request_count
    request_total = inverse_friends.count - mutual_friends.count
  end

  def unread_message_count
    received_messages.where(read: false).count
  end

  def self.authenticate(email, password)
    if user = find_by_email(email)
      if BCrypt::Password.new(user.hashed_password).is_password? password
        return user
      end
    end
    return nil
  end

  def self.find_by_identifier(identifier)
    User.where("lower(username) = ?", identifier.downcase).first ||
      User.where("lower(email) = ?", identifier.downcase).first
  end

  def self.purge_unconfirmed(num)
    User.unscoped.where(confirmed: false).where("updated_at < ?", num.days.ago).destroy_all
  end

private

  def hash_new_password
    unhashed_password = new_password || password
     unless unhashed_password.blank?
       self.hashed_password = BCrypt::Password.create(unhashed_password)
     end
  end

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :confirm, :recover, :home]

  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :correct_users?, only: [:edit, :update, :destroy]

  def home
    if signed_in?
      @micropost = Micropost.new
      @microposts = current_user.all_microposts.includes(comments: [:user, :commentable]).paginate(page: params[:page])
      @activities = current_user.activities.includes(:trackable)
      @friends = current_user.mutual_friends
    else
      redirect_to login_path
    end
  end

  def poll
    respond_to do |format|
      format.html do
        redirect_to root_path
      end
      format.js do

        # load new activities or false
        @new_activities = current_user.activities.where(old: false)
        if @new_activities.count > 0
          @new_activities.load
          current_user.activities.update_all(old: true)

          # load new friends or false
          new_friend_activity = @new_activities.where(trackable_type: 'Friendship').map do |activity|
            friendship = activity.trackable
            current_user?(friendship.user) ? friendship.friend.id : friendship.user.id
          end
          friends_new = current_user.mutual_friends.where(id: new_friend_activity)
          @new_friends = friends_new.count > 0 ? friends_new.load : false
        else
          @new_activities = false
        end
      end
    end
  end

  def show
    @micropost = Micropost.new
    @friendship = nil
    current_user.friendships.each do |friendship|
      @friendship = friendship if friendship.friend_id == @user
    end
    @microposts = @user.microposts.includes(comments: [:user]).paginate(page: params[:page])
  end

  def index
    @search_form = params.has_key?(:search_form) ? SearchForm.new(search_params) : SearchForm.new
    users = if @search_form.search_for.blank?
      User
    else
      User.where(
        "lower(username) LIKE lower(?)",
        "#{Regexp.escape(@search_form.search_for)}%"
      )
    end
    respond_to do |format|
      format.html do
        @users = users.paginate(page: params[:page])
      end
      format.js do
        @users = users.paginate(page: nil)
        render 'users'
      end
    end
  end

  def new
    sign_out unless current_user && current_user.admin
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.confirmation_code = random_code(20)
    if @user.save
      UserMailer.user_confirmation_email(@user).deliver
      redirect_to login_path, notice: 'Please confirm your account via the email sent to you.'
    else
      flash.now[:error] = 'Invalid user info.'
      render 'new'
    end
  end

  def edit
  end

  def update
    params[:user][:new_email] = nil if params[:user][:new_email] == @user.email
    if @user.update_attributes(user_params)
      flash[:success] = "User updated."
      if @user.new_email
        @user.confirmation_code = random_code(20)
        @user.save
        UserMailer.user_confirmation_email(@user).deliver
      end
      sign_in @user
      redirect_to @user
    else
      flash[:error] = "Invalid information."
      render 'edit'
    end
  end

  def destroy
    @user_id = @user.id
    @user.destroy
    respond_to do |format|
      format.html do
        flash[:success] = "User deleted."
        redirect_to users_path
      end
      format.js do
      end
    end
  end

  def confirm
    confirmation_code = params.delete(:confirmation_code)
    user_id = params.delete(:user)
    @user = User.unscoped.find(user_id)
    if @user.confirmation_code.empty?
      redirect_to root_url
    elsif @user.confirmation_code == confirmation_code
      @user.confirmation_code = ""
      @user.new_email.blank? ? new_account : new_email 
    end
  end

  def recover
    @user = User.find_by_email(params[:recover][:email].downcase)
    if @user
      new_password = random_code(10)
      @user.update_attributes(password: new_password)
      UserMailer.password_recovery_email(@user, new_password).deliver
      flash[:notice] = "An email has been sent to you with a new, temporary password."
    else
      flash[:error] = "User not found."
    end
    redirect_to root_url
  end

private

  def new_email
    @user.email = @user.new_email
    @user.new_email = nil
    if @user.save
      flash[:success] = "Email successfully updated."
    else
      flash[:error] = "Email failed to update."
    end
    sign_in @user
    redirect_to @user
  end

  def new_account
    @user.confirmed = true
    if @user.save
      flash[:success] = "You may now log in."
    else
      flash[:error] = "Email failed to confirm."
    end
    sign_out
    redirect_to root_url
  end

  def user_params
    params.require(:user).permit(:email, :new_email, :username, :new_password, :new_password_confirmation, :headline, :about)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_users?
    validate_users(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  #Returns the Gravatar (http:// gravatar.com/) for the given user.
  def gravatar_for(user, options = { })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options.delete(:size) { 50 }
    options[:class] = "gravatar " + options.fetch(:class, "")
    options[:alt] ||= user.username
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, options)
  end

end

app/views/users/_delete_confirm.html.haml
/ provide :user to delete

.modal.fade{id: "delete_modal_#{user.id}", role: 'dialog', aria: {hidden: true}}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: {dismiss: "modal"}, aria: {hidden: true}} &times;
        %h4.modal-title Confirm Delete
      .modal-body
        %p Are you sure you would like to delete the user?
      .modal-footer
        = link_to "Delete User", user_path(user.id), method: :delete, class: "btn btn-primary", remote: true
        %button.btn.btn-default{data: {dismiss: "modal"}} Cancel

app/views/users/_fields.html.haml
- email = params[:action] == 'edit' ? :new_email : :email

.row
  .col-sm-4
    %div{data: {toggle: "tooltip"}, title: "Email addresses must be confirmed via an email to the account."}
      = f.input email, input_html: { value: @user.email, autofocus: true }, label: "Email"

    = f.input :username

    = f.input :new_password, as: :password, label: "Password"


    = f.input :new_password_confirmation, as: :password, label: "Confirm Password"

  .col-sm-8
    = f.input :headline

    = f.input :about, as: :text

app/views/users/_user.html.haml
= content_tag :div, class: "panel panel-default", id: "user_#{user.id}" do
  .panel-heading
    - if current_user.admin
      %a{href: "#delete_modal_#{user.id}", type: 'button', class: 'close', data: {toggle: 'modal'}} &times;
    = link_to user do
      = content_tag :h3, user.username, class: "panel-title"
  .panel-body
    .container
      .row
        = render 'layouts/user_sm', user: user
      - unless current_user?(user) || current_user.friends.include?(user)
        .row
          .btn-group.pull-right
            = link_to "Add Friend", friendships_path(friend_id: user), method: :post, class: "btn btn-success"
= render 'delete_confirm', user: user

app/views/users/_users.html.haml
= render users
.pull-right
  = will_paginate users

app/views/users/destroy.js.erb
// hide confirmation modal
$('#delete_modal_<%= @user_id %>').modal('hide');

// delete user div
$('div').remove('#user_<%= @user_id %>');

app/views/users/edit.html.haml
- provide :title, 'Edit User'

= simple_form_for @user, html: { role: "form" } do |f|
  = render 'fields', f: f
  .row
    = f.submit "Update User", class: "btn btn-primary btn-block"

app/views/users/home.html.haml
- provide :title, "The Network"

#home_wrap.container-fluid
  .row
    .col-sm-8.col-xs-12
      %h2 Latest Posts
      = render 'microposts/new'
      - if @microposts.empty?
        %p Apparently you either have no friends or they are too lazy to post anything.
      - else
        = render @microposts
        .pull-right
          = will_paginate @microposts
    .col-sm-4
      .hidden-xs
        .row
          %h2 Recent Activity
          #activities
            = render 'activities/list', activities: @activities
        .row
          %h2 Friends
          #friends
            = render 'friendships/list', friends: @friends

app/views/users/index.html.haml
- provide :title, 'Users'

- content_for :header do
  .row
    %h1.col-sm-8.col-md-9 Users
    = render 'layouts/search', url: users_path

.searchable
  = render 'users', users: @users

app/views/users/new.html.haml
- provide :title, 'New User'

= simple_form_for @user, html: { role: "form" } do |f|
  = render 'fields', f: f
  .row
    = f.submit "Create User", class: "btn btn-primary btn-block"

app/views/users/poll.js.erb
// update badges in header
<% links = header_links %>
$('#<%=j links[:friends][:id]%>').html('<%=j raw(links[:friends][:text])%>');
$('#<%=j links[:messages][:id]%>').html('<%=j raw(links[:messages][:text])%>');

// update activities
<% if @new_activities %>
  var home_activities = $('#home_activities');
  if(home_activities.length > 0) {
    <% @new_activities.each do |activity| %>
      home_activities.prepend('<%= j render(partial: 'activities/activity', locals: {activity: activity}) %>');
    <% end %>
  } else {
    $('#activities').html('<%= j render(partial: 'activities/list', locals: {activities: @new_activities})%>');
  }
<% end %>

// update friends
<% if @new_friends %>
  var home_friends = $('#home_friends');
  if(home_friends.length > 0) {
    <% @new_friends.each do |friend| %>
      home_friends.prepend('<%= j render(partial: 'friendships/friend', locals: {friend: friend}) %>');
    <% end %>
  } else {
    $('#friends').html('<%= j render(partial: 'friendships/list', locals: {friends: @new_friends}) %>');
  }
<% end %>

app/views/users/show.html.haml
- provide :title, @user.username
- content_for :header do
  .row
    %h1.col-sm-10
      = @user.username
      = content_tag :small, (h @user.headline)
    .btn-group.col-sm-2
      %button{type: 'button', class: 'btn btn-primary dropdown-toggle pull-right', data: {toggle: 'dropdown'}}
        Options
        %span.caret
      %ul{class: 'dropdown-menu', role: 'menu'}
        - if current_user != @user
          %li
            = link_to "Send Message", messages_path(recipient: @user.username, active_tab: :new)
        - if current_user == @user
          %li
            = link_to "Edit", edit_user_path(@user)
        - elsif @friendship
          %li
            = link_to "Remove Friend", friendship_path(@user), method: :delete
        - else
          %li
            = link_to "Add Friend", friendships_path(friend_id: @user), method: :post
        - if current_user.admin
          %li
            %a{href: "#delete_modal_#{@user.id}", data: {toggle: "modal"}} Delete
.row
  .col-md-4
    = gravatar_for @user, size: 250, class: "img-responsive"
  .col-md-8
    %h2 About
    = h @user.about
- if valid_users?(@user, *@user.mutual_friends)
  .row
    %h2 Posts
    - if current_user? @user
      = render 'microposts/new'
    = render @microposts, user: @user
    .pull.right
      = will_paginate @microposts

  = render 'delete_confirm', user: @user

app/views/users/users.js.erb
$('.searchable').html('<%= j render(partial: 'users', locals: {users: @users}) %>');