config/routes.rb
MyPage::Application.routes.draw do
  # root
  root to: 'users#home'

  # polling
  get 'users/poll' => 'users#poll'

  # activities
  resources :activities

  # comments
  resources :comments

  # friendships
  get 'friends' => 'friendships#friends'
  get 'friendships/requests' => 'friendships#requests'
  get 'friendships/pending' => 'friendships#pending'
  resources :friendships

  # messages
  get 'messages/received' => 'messages#received'
  get 'messages/sent' => 'messages#sent'
  resources :messages

  # microposts
  resources :microposts do
    resources :comments
  end

  # sesssions
  post 'login' => 'sessions#create'
  get 'login'  => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  resource :sessions

  # users
  get 'confirm' => 'users#confirm'
  get 'recover' => 'users#recover'
  resources :users

end

app/models/friendship.rb
# == Schema Information
#
# Table name: friendships
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  friend_id  :integer
#  created_at :datetime
#  updated_at :datetime
#

class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"

  has_many :activities, as: :trackable
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @friendship = if params.has_key? :friend_id
      current_user.friendships.build(friend_id: params.delete(:friend_id))
    else
      current_user.friendships.build(friend_id: params.delete(:user_id))
    end
    @valid = @friendship.save
    track_activity @friendship, [@friendship.user, @friendship.friend] if @valid
    respond_to do |format|
      format.html do
        if @valid
          flash[:success] = "Friended #{@friendship.friend.username}."
        else
          flash[:error] = "Unable to add friend."
        end
        redirect_to :back
      end
      format.js do
        if current_user.mutual_friends.include? @friendship.friend
          @new_friend = @friendship.friend
          inverse_friendship = current_user.inverse_friendships.where(user: @friendship.friend).first
          @new_activity = current_user.activities.where(trackable_id: @friendship).first
          @activity = current_user.activities.where(trackable_id: inverse_friendship).first
        end
      end
    end
  end

  def destroy
    @friendship = current_user.friendships.find_by_friend_id(params[:id])
    @inverse_friendship = current_user.inverse_friendships.find_by_user_id(params[:id])
    activity = current_user.activities.where(trackable: @inverse_friendship).first unless @inverse_friendship.nil?
    @activity_id = activity.id if activity
    activity.try(:destroy)
    friend = User.find(params[:id])
    message = "Unfriended #{ friend.username }."

    # destroy friendships
    begin
      @friendship.destroy
    rescue
      message = "Rejected #{ friend.username }'s friend request."
    end
    begin
      @inverse_friendship.destroy
    rescue
      message = "Cancelled your friend request to #{ friend.username }."
    end

    respond_to do |format|
      format.html do
        flash[:success] = message
        redirect_to :back
      end
      format.js do
      end
    end
  end

  def index
    @search_form = params.has_key?(:search_form) ? SearchForm.new(search_params) : SearchForm.new
    @active_tab = params.delete(:active_tab) || session.delete(:active_tab) || 'mutual'
    @mutual = current_user.mutual_friends
    @requests = current_user.friend_requests
    @pending = current_user.pending_friends
    unless @search_form.search_for.blank?
      @mutual = @mutual.where(
        "lower(username) LIKE lower(?)",
        "#{Regexp.escape(@search_form.search_for)}%"
      )
      @requests = @requests.where(
        "lower(username) LIKE lower(?)",
        "#{Regexp.escape(@search_form.search_for)}%"
      )
      @pending = @pending.where(
        "lower(username) LIKE lower(?)",
        "#{Regexp.escape(@search_form.search_for)}%"
      )
    end
    respond_to do |format|
      format.html do
        @mutual = @mutual.paginate(page: params[:mutual_page])
        @requests = @requests.paginate(page: params[:requests_page])
        @pending = @pending.paginate(page: params[:pending_page])
      end
      format.js do
        @mutual = @mutual.paginate(page: nil)
        @requests = @requests.paginate(page: nil)
        @pending = @pending.paginate(page: nil)
        render 'friends'
      end
    end
  end

  def friends
    session[:active_tab] = 'mutual'
    redirect_to friendships_path
  end

  def requests
    session[:active_tab] = 'requests'
    redirect_to friendships_path
  end

  def pending
    session[:active_tab] = 'pending'
    redirect_to friendships_path
  end

end

app/views/friendships/_friend.html.haml
%tr
  %td= link_to friend.username, friend
  %td
    .pull-right
      = link_to new_message_path(recipient: friend.username), class: "btn btn-sm btn-primary" do
        %span.glyphicon.glyphicon-envelope
        Message

app/views/friendships/_friendship.html.haml
.panel.panel-default
  .panel-heading
    = link_to friend do
      = content_tag :h3, friend.username, class: "panel-title"
  .panel-body
    .container
      .row
        = render 'layouts/user_sm', user: friend
      .row
        .btn-group.pull-right
          = link_to "Message", new_message_path(recipient: friend.username), class: "btn btn-primary"
          = link_to "Unfriend", "#unfriend_modal_#{friend.id}", type: 'button', class: 'btn btn-danger', data: {toggle: 'modal'}

.modal.fade{id: "unfriend_modal_#{friend.id}", role: 'dialog', aria: {hidden: true}}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: {dismiss: "modal"}, aria: {hidden: true}} &times;
        = content_tag :h4, "Unfriend #{friend.username}", class: 'modal-title'
      .modal-body
        = content_tag :p, "Are you sure you would like to unfriend #{friend.username}?"
      .modal-footer
        = link_to "Unfriend", friendship_path(friend), method: :delete, class: "btn btn-primary"
        %button.btn.btn-default{data: {dismiss: "modal"}} Cancel

app/views/friendships/_friendships.html.haml
= render partial: 'friendship', collection: mutual, as: :friend
.pull-right
  = will_paginate mutual, param_name: :mutual_page, params: {active_tab: "mutual"}

app/views/friendships/_list.html.haml
- if friends.empty?
  You don't have any friends :(
- else
  %table#home_friends.table
    - friends.each do |friend|
      = render 'friendships/friend', friend: friend

app/views/friendships/_pending.html.haml
.panel.panel-default
  .panel-heading
    = link_to friend do
      = content_tag :h3, friend.username, class: "panel-title"
  .panel-body
    .container
      .row
        = render 'layouts/user_sm', user: friend
      .row
        .btn-group.pull-right
          = link_to "Message", new_message_path(recipient: friend.username), class: "btn btn-primary"
          = link_to 'Cancel Request', friendship_path(friend), method: :delete, class: 'btn btn-danger'

.modal.fade{id: "cancel_modal_#{friend.id}", role: 'dialog', aria: {hidden: true}}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: {dismiss: "modal"}, aria: {hidden: true}} &times;
        = content_tag :h4, "Cancel request to #{friend.username}", class: 'modal-title'
      .modal-body
        = content_tag :p, "Are you sure you would like to cancel your friend request to #{friend.username}?"
      .modal-footer
        = link_to "Cancel Request", friendship_path(friend), method: :delete, class: "btn btn-primary"
        %button.btn.btn-default{data: {dismiss: "modal"}} Maintain Request

app/views/friendships/_pendings.html.haml
= render partial: 'pending', collection: pending, as: :friend
.pull-right
  = will_paginate pending, param_name: :pending_page, params: {active_tab: "pending"}

app/views/friendships/_request.html.haml
.panel.panel-default
  .panel-heading
    = link_to user do
      = content_tag :h3, user.username, class: "panel-title"
  .panel-body
    .container
      .row
        = render 'layouts/user_sm', user: user
      .row
        .btn-group.pull-right
          = link_to "Message", new_message_path(recipient: user.username), class: "btn btn-primary"
          = link_to 'Approve', friendships_path(user_id: user), method: :post, type: 'button', class: 'btn btn-success'
          = link_to 'Reject', "#reject_modal_#{user.id}", type: 'button', class: 'btn btn-danger', data: {toggle: 'modal'}

.modal.fade{id: "reject_modal_#{user.id}", role: 'dialog', aria: {hidden: true}}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: {dismiss: "modal"}, aria: {hidden: true}} &times;
        = content_tag :h4, "Reject #{user.username}", class: 'modal-title'
      .modal-body
        = content_tag :p, "Are you sure you would like to reject #{user.username}'s request?"
      .modal-footer
        = link_to "Reject", friendship_path(user), method: :delete, class: "btn btn-primary"
        %button.btn.btn-default{data: {dismiss: "modal"}} Cancel

app/views/friendships/_requests.html.haml
= render partial: 'request', collection: requests, as: :user
.pull-right
  = will_paginate requests, param_name: :requests_page, params: {active_tab: "requests"}

app/views/friendships/create.js.erb
$('#activity_<%= @activity.id %>').html('<%= j raw(ActivityPresenter.new(@activity, self).render_activity)%>');
$('#activity_<%= @activity.id %>').closest('tr').before('<%= j render(partial: 'activities/activity', locals: {activity: @new_activity}) %>');

<% if @new_friend %>
  var home_friends = $('#home_friends');
  if(home_friends.length > 0) {
    home_friends.prepend('<%= j render(partial: 'friendships/friend', locals: {friend: @new_friend}) %>');
  } else {
    $('#friends').html('<%= j render(partial: 'friendships/list', locals: {friends: [@new_friend]}) %>');
  }
<% end %>

app/views/friendships/destroy.js.erb
<% if @activity_id %>
  $('#activity_<%= @activity_id %>').closest('tr').remove();
<% end %>

app/views/friendships/friends.js.erb
$('div.mutual.searchable').html('<%= j render(partial: 'friendships', locals: {mutual: @mutual}) %>');
$('div.requests.searchable').html('<%= j render(partial: 'requests', locals: {requests: @requests}) %>');
$('div.pending.searchable').html('<%= j render(partial: 'pendings', locals: {pending: @pending}) %>');

app/views/friendships/index.html.haml
- provide :title, "Friends"

- content_for :header do
  .row
    %h1.col-sm-8.col-md-9 Friends
    = render 'layouts/search', url: friendships_path

%ul#friendship_tabs.nav.nav-tabs
  = content_tag :li, class: (@active_tab == "mutual" ? "active" : "") do
    %a{href: "#mutual", data: {toggle: "tab"}} Mutual
  = content_tag :li, class: (@active_tab == "requests" ? "active" : "") do
    %a{href: "#requests", data: {toggle: "tab"}} Requests
  = content_tag :li, class: (@active_tab == "pending" ? "active" : "") do
    %a{href: "#pending", data: {toggle: "tab"}} Pending

.tab-content
  = content_tag :div, id: 'mutual', class: "tab-pane#{' active' if @active_tab == 'mutual'}" do
    %br
    - if @mutual.blank?
      %h2 No friends :(
    - else
      .mutual.searchable
        = render 'friendships', mutual: @mutual

  = content_tag :div, id: 'requests', class: "tab-pane#{' active' if @active_tab == 'requests'}" do
    %br
    - if @requests.blank?
      %h2 No one is awaiting approval from you
    - else
      .requests.searchable
        = render 'requests', requests: @requests

  = content_tag :div, id: 'pending', class: "tab-pane#{' active' if @active_tab == 'pending'}" do
    %br
    - if @pending.blank?
      %h2 You are not awaiting approval from anyone
    - else
      .pending.searchable
        = render 'pendings', pending: @pending